Controllers/AsociadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcClinicas.Data;
using MvcClinicas.Models;

namespace MvcClinicas.Controllers
{
    public class AsociadosController : Controller
    {
        private readonly MvcMovieContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public AsociadosController(MvcMovieContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Asociados
        public async Task<IActionResult> Index()
        {
              return _context.Asociado != null ? 
                          View(await _context.Asociado.ToListAsync()) :
                          Problem("Entity set 'MvcMovieContext.Asociado'  is null.");
        }

        // GET: Asociados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Asociado == null)
            {
                return NotFound();
            }

            var asociado = await _context.Asociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asociado == null)
            {
                return NotFound();
            }
            //Poner aqui el ID del asociado
            TempData["IdAsociado"] = id.ToString();
            return View(asociado);
        }

        


        // GET: Asociados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Asociados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FolioCredencial,Nombre,FechaAlta,Sexo,FechaNacimiento,Edad,NombrePadre,NombreMadre,Direccion,Ciudad,Estado,Pais,CP,Telefono1,Telefono2,Telefono3,Telefono4,CorreoElectronico,Emergencias,Activo")] Asociado asociado)
        {
            if (ModelState.IsValid)
            {
                            //Save image to wwwroot/image
            // string wwwRootPath = _hostEnvironment.WebRootPath;
            // string fileName = Path.GetFileNameWithoutExtension(asociado.ImageFile.FileName);
            // string extension = Path.GetExtension(asociado.ImageFile.FileName);
            // asociado.ImageName=fileName =  fileName + DateTime.Now.ToString("yymmssfff") + extension;
            // string path = Path.Combine(wwwRootPath + "/Image/", fileName);
            // using (var fileStream = new FileStream(path,FileMode.Create))
            // {
            //     await asociado.ImageFile.CopyToAsync(fileStream);
            // }
                _context.Add(asociado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(asociado);
        }

        // GET: Asociados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Asociado == null)
            {
                return NotFound();
            }

            var asociado = await _context.Asociado.FindAsync(id);
            if (asociado == null)
            {
                return NotFound();
            }
            return View(asociado);
        }

        // POST: Asociados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FolioCredencial,Nombre,FechaAlta,Sexo,FechaNacimiento,Edad,NombrePadre,NombreMadre,Direccion,Ciudad,Estado,Pais,CP,Telefono1,Telefono2,Telefono3,Telefono4,CorreoElectronico,Emergencias,Activo")] Asociado asociado)
        {
            if (id != asociado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asociado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsociadoExists(asociado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(asociado);
        }

        // GET: Asociados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Asociado == null)
            {
                return NotFound();
            }

            var asociado = await _context.Asociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asociado == null)
            {
                return NotFound();
            }

            return View(asociado);
        }

        // POST: Asociados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Asociado == null)
            {
                return Problem("Entity set 'MvcMovieContext.Asociado'  is null.");
            }
            var asociado = await _context.Asociado.FindAsync(id);
            if (asociado != null)
            {
                _context.Asociado.Remove(asociado);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AsociadoExists(int id)
        {
          return (_context.Asociado?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/PadecimientoAsociadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcClinicas.Data;
using MvcClinicas.Models;

namespace MvcClinicas.Controllers
{
    public class PadecimientoAsociadoController : Controller
    {
        private readonly MvcMovieContext _context;

        public PadecimientoAsociadoController(MvcMovieContext context)
        {
            _context = context;
        }

        // GET: PadecimientoAsociado
        public async Task<IActionResult> Index()
        {
              return _context.PadecimientoAsociado != null ? 
                          View(await _context.PadecimientoAsociado.ToListAsync()) :
                          Problem("Entity set 'MvcMovieContext.PadecimientoAsociado'  is null.");
        }

        // GET: PadecimientoAsociado/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PadecimientoAsociado == null)
            {
                return NotFound();
            }

            var padecimientoAsociado = await _context.PadecimientoAsociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (padecimientoAsociado == null)
            {
                return NotFound();
            }

            return View(padecimientoAsociado);
        }

        // GET: PadecimientoAsociado/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: PadecimientoAsociado/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdAsociado,Padecimiento,Hospital,FechaRegistro,Valvula,Sangre,Notas")] PadecimientoAsociado padecimientoAsociado)
        {
            if (ModelState.IsValid)
            {
                if(TempData["IdAsociado"] != null)
                {padecimientoAsociado.IdAsociado = int.Parse(TempData["IdAsociado"].ToString());}
                
                _context.Add(padecimientoAsociado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(padecimientoAsociado);
        }

        // GET: PadecimientoAsociado/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PadecimientoAsociado == null)
            {
                return NotFound();
            }

            var padecimientoAsociado = await _context.PadecimientoAsociado.FindAsync(id);
            if (padecimientoAsociado == null)
            {
                return NotFound();
            }
            return View(padecimientoAsociado);
        }

        // POST: PadecimientoAsociado/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdAsociado,Padecimiento,Hospital,FechaRegistro,Valvula,Sangre,Notas")] PadecimientoAsociado padecimientoAsociado)
        {
            if (id != padecimientoAsociado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(padecimientoAsociado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PadecimientoAsociadoExists(padecimientoAsociado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(padecimientoAsociado);
        }

        // GET: PadecimientoAsociado/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PadecimientoAsociado == null)
            {
                return NotFound();
            }

            var padecimientoAsociado = await _context.PadecimientoAsociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (padecimientoAsociado == null)
            {
                return NotFound();
            }

            return View(padecimientoAsociado);
        }

        // POST: PadecimientoAsociado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PadecimientoAsociado == null)
            {
                return Problem("Entity set 'MvcMovieContext.PadecimientoAsociado'  is null.");
            }
            var padecimientoAsociado = await _context.PadecimientoAsociado.FindAsync(id);
            if (padecimientoAsociado != null)
            {
                _context.PadecimientoAsociado.Remove(padecimientoAsociado);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PadecimientoAsociadoExists(int id)
        {
          return (_context.PadecimientoAsociado?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/PadresAsociadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcClinicas.Data;
using MvcClinicas.Models;

namespace MvcClinicas.Controllers
{
    public class PadresAsociadosController : Controller
    {
        private readonly MvcMovieContext _context;

        public PadresAsociadosController(MvcMovieContext context)
        {
            _context = context;
        }

        // GET: PadresAsociados
        public async Task<IActionResult> Index()
        {
              return _context.PadresAsociado != null ? 
                          View(await _context.PadresAsociado.ToListAsync()) :
                          Problem("Entity set 'MvcMovieContext.PadresAsociado'  is null.");
        }

        // GET: PadresAsociados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PadresAsociado == null)
            {
                return NotFound();
            }

            var padresAsociado = await _context.PadresAsociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (padresAsociado == null)
            {
                return NotFound();
            }

            return View(padresAsociado);
        }

        // GET: PadresAsociados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PadresAsociados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdAsociado,Nombre,LugarNacimiento,Escolaridad,Edad,Tipo,Parentesco,AcidoFolico,CitasMedicas,Seguro")] PadresAsociado padresAsociado)
        {
            if (ModelState.IsValid)
            {
                if(TempData["IdAsociado"] != null)
                {padresAsociado.IdAsociado = int.Parse(TempData["IdAsociado"].ToString());}
                _context.Add(padresAsociado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(padresAsociado);
        }

        // GET: PadresAsociados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PadresAsociado == null)
            {
                return NotFound();
            }

            var padresAsociado = await _context.PadresAsociado.FindAsync(id);
            if (padresAsociado == null)
            {
                return NotFound();
            }
            return View(padresAsociado);
        }

        // POST: PadresAsociados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdAsociado,Nombre,LugarNacimiento,Escolaridad,Edad,Tipo,Parentesco,AcidoFolico,CitasMedicas,Seguro")] PadresAsociado padresAsociado)
        {
            if (id != padresAsociado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(padresAsociado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PadresAsociadoExists(padresAsociado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(padresAsociado);
        }

        // GET: PadresAsociados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PadresAsociado == null)
            {
                return NotFound();
            }

            var padresAsociado = await _context.PadresAsociado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (padresAsociado == null)
            {
                return NotFound();
            }

            return View(padresAsociado);
        }

        // POST: PadresAsociados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PadresAsociado == null)
            {
                return Problem("Entity set 'MvcMovieContext.PadresAsociado'  is null.");
            }
            var padresAsociado = await _context.PadresAsociado.FindAsync(id);
            if (padresAsociado != null)
            {
                _context.PadresAsociado.Remove(padresAsociado);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PadresAsociadoExists(int id)
        {
          return (_context.PadresAsociado?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Asociados/Create.cshtml
@model MvcClinicas.Models.Asociado

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Asociado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FolioCredencial" class="control-label"></label>
                <input asp-for="FolioCredencial" class="form-control" />
                <span asp-validation-for="FolioCredencial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaAlta" class="control-label"></label>
                <input asp-for="FechaAlta" class="form-control" />
                <span asp-validation-for="FechaAlta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePadre" class="control-label"></label>
                <input asp-for="NombrePadre" class="form-control" />
                <span asp-validation-for="NombrePadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreMadre" class="control-label"></label>
                <input asp-for="NombreMadre" class="form-control" />
                <span asp-validation-for="NombreMadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ciudad" class="control-label"></label>
                <input asp-for="Ciudad" class="form-control" />
                <span asp-validation-for="Ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CP" class="control-label"></label>
                <input asp-for="CP" class="form-control" />
                <span asp-validation-for="CP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono1" class="control-label"></label>
                <input asp-for="Telefono1" class="form-control" />
                <span asp-validation-for="Telefono1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono2" class="control-label"></label>
                <input asp-for="Telefono2" class="form-control" />
                <span asp-validation-for="Telefono2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono3" class="control-label"></label>
                <input asp-for="Telefono3" class="form-control" />
                <span asp-validation-for="Telefono3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono4" class="control-label"></label>
                <input asp-for="Telefono4" class="form-control" />
                <span asp-validation-for="Telefono4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emergencias" class="control-label"></label>
                <input asp-for="Emergencias" class="form-control" />
                <span asp-validation-for="Emergencias" class="text-danger"></span>
            </div>

            @* <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div> *@
           
            <div class="form-group">
                <label asp-for="Activo" class="control-label"></label>
                <input asp-for="Activo" class="form-control" />
                <span asp-validation-for="Activo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-link" asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Asociados/Details.cshtml
@model MvcClinicas.Models.Asociado

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Asociado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FolioCredencial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FolioCredencial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombrePadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emergencias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emergencias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a class="btn btn-dark" asp-controller="PadecimientoAsociado" asp-action="Create">Padecimientos</a> |
    <a class="btn btn-light" asp-controller="PadresAsociados" asp-action="Create">Padres Asociado</a> |
    <a class="btn btn-link" asp-action="Index">Regresar</a>
</div>

Views/Asociados/Index.cshtml
@model IEnumerable<MvcClinicas.Models.Asociado>

@{
    ViewData["Title"] = "Index";
}

<h1>Asociados</h1>

<p>
    <a asp-action="Create">Nuevo Asociado</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FolioCredencial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Emergencias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FolioCredencial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Emergencias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                <a class="btn btn-primary btn-sm"  asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a class="btn btn-primary btn-sm" asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a class="btn btn-primary btn-sm" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>